export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "dashboard:view",
  DASHBOARD_ADMIN: "dashboard:admin",

  // Users
  USERS_VIEW: "users:view",
  USERS_CREATE: "users:create",
  USERS_EDIT: "users:edit",
  USERS_DELETE: "users:delete",

  // Trainers
  TRAINERS_VIEW: "trainers:view",
  TRAINERS_CREATE: "trainers:create",
  TRAINERS_EDIT: "trainers:edit",
  TRAINERS_DELETE: "trainers:delete",
  TRAINERS_EVALUATE: "trainers:evaluate",
  TRAINERS_VIEW_OWN: "trainers:view_own",

  // Trainees
  TRAINEES_VIEW: "trainees:view",
  TRAINEES_CREATE: "trainees:create",
  TRAINEES_EDIT: "trainees:edit",
  TRAINEES_DELETE: "trainees:delete",
  TRAINEES_VIEW_OWN: "trainees:view_own",

  // Departments
  DEPARTMENTS_VIEW: "departments:view",
  DEPARTMENTS_CREATE: "departments:create",
  DEPARTMENTS_EDIT: "departments:edit",
  DEPARTMENTS_DELETE: "departments:delete",
  DEPARTMENTS_VIEW_OWN: "departments:view_own",

  // Courses
  COURSES_VIEW: "courses:view",
  COURSES_CREATE: "courses:create",
  COURSES_EDIT: "courses:edit",
  COURSES_DELETE: "courses:delete",

  // Schedules
  SCHEDULES_VIEW: "schedules:view",
  SCHEDULES_CREATE: "schedules:create",
  SCHEDULES_EDIT: "schedules:edit",
  SCHEDULES_VIEW_OWN: "schedules:view_own",

  // Grades
  GRADES_VIEW: "grades:view",
  GRADES_CREATE: "grades:create",
  GRADES_EDIT: "grades:edit",
  GRADES_APPROVE: "grades:approve",
  GRADES_VIEW_OWN: "grades:view_own",

  // Attendance
  ATTENDANCE_VIEW: "attendance:view",
  ATTENDANCE_RECORD: "attendance:record",
  ATTENDANCE_VIEW_OWN: "attendance:view_own",

  // Finance
  FINANCE_VIEW: "finance:view",
  FINANCE_CREATE: "finance:create",
  FINANCE_APPROVE: "finance:approve",
  FINANCE_REPORTS: "finance:reports",

  // Quality - General
  QUALITY_VIEW: "quality:view",
  QUALITY_CREATE: "quality:create",
  QUALITY_EDIT: "quality:edit",
  QUALITY_AUDIT: "quality:audit",

  // Quality - Standards
  QUALITY_STANDARDS_VIEW: "quality:standards_view",
  QUALITY_STANDARDS_MANAGE: "quality:standards_manage",

  // Quality - KPIs
  QUALITY_KPIS_VIEW: "quality:kpis_view",
  QUALITY_KPIS_MANAGE: "quality:kpis_manage",
  QUALITY_KPIS_MEASURE: "quality:kpis_measure",

  // Quality - Audits
  QUALITY_AUDITS_VIEW: "quality:audits_view",
  QUALITY_AUDITS_SCHEDULE: "quality:audits_schedule",
  QUALITY_AUDITS_CONDUCT: "quality:audits_conduct",
  QUALITY_AUDITS_MANAGE_FINDINGS: "quality:audits_manage_findings",

  // Quality - Improvement Plans
  QUALITY_PLANS_VIEW: "quality:plans_view",
  QUALITY_PLANS_CREATE: "quality:plans_create",
  QUALITY_PLANS_APPROVE: "quality:plans_approve",

  // Quality - Surveys
  QUALITY_SURVEYS_VIEW: "quality:surveys_view",
  QUALITY_SURVEYS_CREATE: "quality:surveys_create",
  QUALITY_SURVEYS_ANALYZE: "quality:surveys_analyze",

  // Quality - Reports
  QUALITY_REPORTS_VIEW: "quality:reports_view",
  QUALITY_REPORTS_CREATE: "quality:reports_create",
  QUALITY_REPORTS_APPROVE: "quality:reports_approve",

  // Quality - Documents & Accreditations
  QUALITY_DOCS_MANAGE: "quality:docs_manage",
  QUALITY_ACCREDITATIONS_MANAGE: "quality:accreditations_manage",

  // HR
  HR_VIEW: "hr:view",
  HR_CREATE: "hr:create",
  HR_EDIT: "hr:edit",
  HR_PAYROLL: "hr:payroll",

  // Tasks
  TASKS_VIEW: "tasks:view",
  TASKS_CREATE: "tasks:create",
  TASKS_EDIT: "tasks:edit",
  TASKS_ASSIGN: "tasks:assign",
  TASKS_VIEW_OWN: "tasks:view_own",

  // Projects
  PROJECTS_VIEW: "projects:view",
  PROJECTS_CREATE: "projects:create",
  PROJECTS_EDIT: "projects:edit",
  PROJECTS_DELETE: "projects:delete",

  // E-Learning
  ELEARNING_VIEW: "elearning:view",
  ELEARNING_CREATE: "elearning:create",
  ELEARNING_EDIT: "elearning:edit",
  ELEARNING_TAKE_EXAM: "elearning:take_exam",

  // Research
  RESEARCH_VIEW: "research:view",
  RESEARCH_CREATE: "research:create",
  RESEARCH_EDIT: "research:edit",

  // Community
  COMMUNITY_VIEW: "community:view",
  COMMUNITY_CREATE: "community:create",
  COMMUNITY_EDIT: "community:edit",

  // Reports
  REPORTS_VIEW: "reports:view",
  REPORTS_CREATE: "reports:create",
  REPORTS_EXPORT: "reports:export",

  // Notifications
  NOTIFICATIONS_VIEW: "notifications:view",
  NOTIFICATIONS_SEND: "notifications:send",
  NOTIFICATIONS_BROADCAST: "notifications:broadcast",

  // Settings
  SETTINGS_VIEW: "settings:view",
  SETTINGS_EDIT: "settings:edit",
  SETTINGS_ADMIN: "settings:admin",

  // AI Features
  AI_VIEW: "ai:view",
  AI_CHAT: "ai:chat",
  AI_INSIGHTS: "ai:insights",
  AI_EARLY_WARNING: "ai:early_warning",
  AI_REPORTS: "ai:reports",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  DEAN: "dean",
  VP_TRAINERS: "vp_trainers",
  VP_TRAINEES: "vp_trainees",
  VP_QUALITY: "vp_quality",
  DEPT_HEAD: "dept_head",
  TRAINER: "trainer",
  TRAINEE: "trainee",
  ACCOUNTANT: "accountant",
  QUALITY_OFFICER: "quality_officer",
  HR_MANAGER: "hr_manager",
  IT_ADMIN: "it_admin",
  UNIT_COORDINATOR: "unit_coordinator",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  [ROLES.DEAN]: ALL_PERMISSIONS,

  [ROLES.VP_TRAINERS]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TRAINERS_VIEW,
    PERMISSIONS.TRAINERS_CREATE,
    PERMISSIONS.TRAINERS_EDIT,
    PERMISSIONS.TRAINERS_EVALUATE,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_CREATE,
    PERMISSIONS.SCHEDULES_EDIT,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.GRADES_APPROVE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_ASSIGN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
    PERMISSIONS.AI_EARLY_WARNING,
    PERMISSIONS.AI_REPORTS,
  ],

  [ROLES.VP_TRAINEES]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TRAINEES_VIEW,
    PERMISSIONS.TRAINEES_CREATE,
    PERMISSIONS.TRAINEES_EDIT,
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.GRADES_APPROVE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_ASSIGN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.ELEARNING_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
    PERMISSIONS.AI_EARLY_WARNING,
    PERMISSIONS.AI_REPORTS,
  ],

  [ROLES.VP_QUALITY]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.QUALITY_VIEW,
    PERMISSIONS.QUALITY_CREATE,
    PERMISSIONS.QUALITY_EDIT,
    PERMISSIONS.QUALITY_AUDIT,
    // Quality granular permissions (all)
    PERMISSIONS.QUALITY_STANDARDS_VIEW,
    PERMISSIONS.QUALITY_STANDARDS_MANAGE,
    PERMISSIONS.QUALITY_KPIS_VIEW,
    PERMISSIONS.QUALITY_KPIS_MANAGE,
    PERMISSIONS.QUALITY_KPIS_MEASURE,
    PERMISSIONS.QUALITY_AUDITS_VIEW,
    PERMISSIONS.QUALITY_AUDITS_SCHEDULE,
    PERMISSIONS.QUALITY_AUDITS_CONDUCT,
    PERMISSIONS.QUALITY_AUDITS_MANAGE_FINDINGS,
    PERMISSIONS.QUALITY_PLANS_VIEW,
    PERMISSIONS.QUALITY_PLANS_CREATE,
    PERMISSIONS.QUALITY_PLANS_APPROVE,
    PERMISSIONS.QUALITY_SURVEYS_VIEW,
    PERMISSIONS.QUALITY_SURVEYS_CREATE,
    PERMISSIONS.QUALITY_SURVEYS_ANALYZE,
    PERMISSIONS.QUALITY_REPORTS_VIEW,
    PERMISSIONS.QUALITY_REPORTS_CREATE,
    PERMISSIONS.QUALITY_REPORTS_APPROVE,
    PERMISSIONS.QUALITY_DOCS_MANAGE,
    PERMISSIONS.QUALITY_ACCREDITATIONS_MANAGE,
    // Other permissions
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.TRAINERS_VIEW,
    PERMISSIONS.TRAINEES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_CREATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
    PERMISSIONS.AI_REPORTS,
  ],

  [ROLES.DEPT_HEAD]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DEPARTMENTS_VIEW_OWN,
    PERMISSIONS.TRAINERS_VIEW,
    PERMISSIONS.TRAINEES_VIEW,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_EDIT,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_CREATE,
    PERMISSIONS.SCHEDULES_EDIT,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.GRADES_APPROVE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_ASSIGN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.ELEARNING_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
    PERMISSIONS.AI_EARLY_WARNING,
  ],

  [ROLES.TRAINER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TRAINERS_VIEW_OWN,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.SCHEDULES_VIEW_OWN,
    PERMISSIONS.GRADES_VIEW,
    PERMISSIONS.GRADES_CREATE,
    PERMISSIONS.GRADES_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_RECORD,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.ELEARNING_VIEW,
    PERMISSIONS.ELEARNING_CREATE,
    PERMISSIONS.ELEARNING_EDIT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
  ],

  [ROLES.TRAINEE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TRAINEES_VIEW_OWN,
    PERMISSIONS.COURSES_VIEW,
    PERMISSIONS.SCHEDULES_VIEW_OWN,
    PERMISSIONS.GRADES_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.ELEARNING_VIEW,
    PERMISSIONS.ELEARNING_TAKE_EXAM,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_REPORTS,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
  ],

  [ROLES.QUALITY_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.QUALITY_VIEW,
    PERMISSIONS.QUALITY_CREATE,
    PERMISSIONS.QUALITY_EDIT,
    PERMISSIONS.QUALITY_AUDIT,
    // Quality granular permissions (most, excluding approve/accreditations)
    PERMISSIONS.QUALITY_STANDARDS_VIEW,
    PERMISSIONS.QUALITY_KPIS_VIEW,
    PERMISSIONS.QUALITY_KPIS_MANAGE,
    PERMISSIONS.QUALITY_KPIS_MEASURE,
    PERMISSIONS.QUALITY_AUDITS_VIEW,
    PERMISSIONS.QUALITY_AUDITS_SCHEDULE,
    PERMISSIONS.QUALITY_AUDITS_CONDUCT,
    PERMISSIONS.QUALITY_AUDITS_MANAGE_FINDINGS,
    PERMISSIONS.QUALITY_PLANS_VIEW,
    PERMISSIONS.QUALITY_PLANS_CREATE,
    PERMISSIONS.QUALITY_SURVEYS_VIEW,
    PERMISSIONS.QUALITY_SURVEYS_CREATE,
    PERMISSIONS.QUALITY_SURVEYS_ANALYZE,
    PERMISSIONS.QUALITY_REPORTS_VIEW,
    PERMISSIONS.QUALITY_REPORTS_CREATE,
    PERMISSIONS.QUALITY_DOCS_MANAGE,
    // Other permissions
    PERMISSIONS.DEPARTMENTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_CREATE,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
  ],

  [ROLES.HR_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_PAYROLL,
    PERMISSIONS.TRAINERS_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
    PERMISSIONS.AI_INSIGHTS,
  ],

  [ROLES.IT_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ADMIN,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.SETTINGS_ADMIN,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.NOTIFICATIONS_BROADCAST,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [ROLES.UNIT_COORDINATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TASKS_VIEW_OWN,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_CHAT,
  ],
};

export function hasPermission(
  userPermissions: Permission[],
  requiredPermission: Permission
): boolean {
  return userPermissions.includes(requiredPermission);
}

export function hasAnyPermission(
  userPermissions: Permission[],
  requiredPermissions: Permission[]
): boolean {
  return requiredPermissions.some((p) => userPermissions.includes(p));
}

export function hasAllPermissions(
  userPermissions: Permission[],
  requiredPermissions: Permission[]
): boolean {
  return requiredPermissions.every((p) => userPermissions.includes(p));
}

export function getPermissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}
